import { Component, OnInit } from '@angular/core';
// import { HeaderService } from '../header.service';
import { NavigationExtras, Router } from '@angular/router';
// import { EmpanelmentmasterserviceService } from '../Services/empanelmentmasterservice.service';
import Swal from 'sweetalert2';
import autoTable from 'jspdf-autotable';
// import { TableUtil } from '../util/TableUtil';
import jsPDF from 'jspdf';
import { DatePipe } from '@angular/common';
import { HeaderService } from '../../header.service';
import { EmpanelmentmasterserviceService } from '../../Services/empanelmentmasterservice.service';
import { TableUtil } from '../../util/TableUtil';
import { SessionStorageService } from 'src/app/services/session-storage.service';


@Component({
  selector: 'app-typeofexpertiseview',
  templateUrl: './typeofexpertiseview.component.html',
  styleUrls: ['./typeofexpertiseview.component.scss']
})
export class TypeofexpertiseviewComponent implements OnInit {
  txtsearchDate: any;
  typeofexpertiselist: any = [];
  currentPage: any;
  pageElement: any;
  showPegi: boolean;
  record: any;
  user: any;

  constructor(public route: Router,
    public headerService: HeaderService,
    private empanelmentmasterservice: EmpanelmentmasterserviceService,private sessionService: SessionStorageService) { }

  ngOnInit(): void {
    this.headerService.setTitle('View Type Of Expertise');
    this.user = this.sessionService.decryptSessionData("user");
    console.log(this.user);

    this.currentPage = 1;
    this.pageElement = 50;
    this.getallexspertisetype();
  }
  swal(title: any, text: any, icon: any) {
    Swal.fire({
      icon: icon,
      title: title,
      text: text
    });
  }

  onPageBoundsCorrection(number: number) {
    this.currentPage = number;
  }

  getallexspertisetype() {
    this.empanelmentmasterservice.getallexpertisetypelist().subscribe(data => {
      this.typeofexpertiselist = data;
      this.record = this.typeofexpertiselist.length;
      console.log(this.typeofexpertiselist);
      if (this.record > 0) {
        this.showPegi = true;
      } else {
        this.showPegi = false;
      }
      console.log(this.typeofexpertiselist)
    });
  }
  edit(item: any) {
    let navigationExtras: NavigationExtras = {
      state: {
        user: item
      }
    };
    this.route.navigate(['application/typeofexpertise'], navigationExtras);
  }
  report: any = [];
  expertise: any = {
    Slno: '',
    Medexpertisename: '',
    Typexpertisename: '',
    fullname: "",
    createdate: "",
    statusFlag: '',
  };
  heading = [['Sl#', 'Medical Expertise Name', 'Type Of Expertise Name', 'Created BY', 'Created On', 'Status']];

  downloadList(type) {

    this.report = [];
    let item: any;
    for (var i = 0; i < this.typeofexpertiselist.length; i++) {
      item = this.typeofexpertiselist[i];
      this.expertise = [];
      this.expertise.slNo = i + 1;
      this.expertise.Medexpertisename = item.medexpertiseid.medexpertisename;
      this.expertise.Typexpertisename = item.typeofexpertisename;
      this.expertise.fullname = item.createdby.fullname;
      this.expertise.createdate = this.convertDate(item.createdate);
      if (item.status == 0) {
        this.expertise.statusFlag = 'Active';
      } else {
        this.expertise.statusFlag = 'Inactive';
      }
      this.report.push(this.expertise);
      console.log(this.report);
    }
    if (type == 1) {
      let filter = [];
      TableUtil.exportListToExcelWithFilter(
        this.report,
        ' Medical Expertise List',
        this.heading,
        filter
      );
    } else if (type == 2) {
      if (this.report == null || this.report.length == 0) {
        this.swal('Info', 'No Record Found', 'info');
        return;
      }
      var doc = new jsPDF('l', 'mm', [260, 240]);
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text(' Medical Expertise  List', 110, 10);
      doc.setFontSize(12);
      doc.text('Generated On: ' + this.convertDate(new Date()), 25, 33);
      doc.text(
        'Generated By: ' + this.user.fullName,
        140,
        33
      );
      var rows = [];
      for (var i = 0; i < this.report.length; i++) {
        var clm = this.report[i];
        var pdf = [];
        pdf[0] = clm.slNo;
        pdf[1] = clm.Medexpertisename;
        pdf[2] = clm.Typexpertisename;
        pdf[3] = clm.fullname;
        pdf[4] = clm.createdate;
        pdf[5] = clm.statusFlag;
        rows.push(pdf);
      }
      console.log(rows);
      autoTable(doc, {
        head: this.heading,
        body: rows,
        theme: 'grid',
        startY: 40,
        headStyles: {
          fillColor: [26, 99, 54],
        },
        columnStyles: {
          0: { cellWidth: 40 },
          1: { cellWidth: 40 },
          2: { cellWidth: 40 },
          3: { cellWidth: 40 },
          4: { cellWidth: 40 },
          5: { cellWidth: 40 },

        },
      });
      doc.save('GJAY_ Type_Of_Medical Expertise List.pdf');
    }
  }
  convertDate(date) {
    var datePipe = new DatePipe('en-US');
    date = datePipe.transform(date, 'dd-MMM-yyyy hh:mm:ss a');
    return date;
  }
  delete(item: any) {
    Swal.fire({
      title: 'Are you sure?',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete it!'
    }).then((result) => {
      if (result.isConfirmed) {
        this.empanelmentmasterservice.delete(item).subscribe(data => {
          if (data == 1) {
            this.swal("Deleted!", "Record has been Inactivate", "success");
          } else if (data == "") {
            this.swal("Error", "Some error happen", "error");
          }
          this.getallexspertisetype();
        });
      }
    })

  }
}
