import { DatePipe } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormBuilder } from '@angular/forms';
import { NavigationExtras, Router } from '@angular/router';
import jsPDF from 'jspdf';
import { HeaderService } from '../../header.service';
import { GrievanceByService } from '../../Services/grievance-by.service';
import { TableUtil } from '../../util/TableUtil';
import autoTable from 'jspdf-autotable';
import Swal from 'sweetalert2';
import { SessionStorageService } from 'src/app/services/session-storage.service';

@Component({
  selector: 'app-grievance-by-view',
  templateUrl: './grievance-by-view.component.html',
  styleUrls: ['./grievance-by-view.component.scss']
})
export class GrievanceByViewComponent implements OnInit {
  txtsearchDate: any;
  record: any;
  currentPage: any;
  pageElement: any;
  showPegi: boolean;
  user: any;
  packageData: any = [];
  deleteDetails: any;
  status: any;
  id: any;
  constructor(private route: Router, public formBuilder: FormBuilder, public headerService: HeaderService, private grievancebyService: GrievanceByService, private sessionService: SessionStorageService) { }

  ngOnInit(): void {
    this.currentPage = 1;
    this.pageElement = 50;
    this.headerService.setTitle("View Grievance By");
    this.user = this.sessionService.decryptSessionData("user");
    this.getGrievanceByDetails();
  }
  getGrievanceByDetails() {
    this.grievancebyService.getlist().subscribe((allData) => {
      this.packageData = allData;
      this.record = this.packageData.length;
      if (this.record > 0) {
        this.showPegi = true;
      }
      else {
        this.showPegi = false;
      }
    })
  }
  edit(id: any) {
    let navigateExtras: NavigationExtras = {
      state: {
        item: id
      }
    };
    this.route.navigate(['application/grievanceby'], navigateExtras)
  }
  onPageBoundsCorrection(number: number) {
    this.currentPage = number;
  }

  report: any = [];
  grievanceBy: any = {
    Slno: "",
    grivancename: "",
    fullname: "",
    screatedate: "",
    statusFlag: ""
  };
  heading = [['Sl#', 'Grievance BY', 'Created BY', 'Created On', 'Status']];

  downloadList(type) {
    // this.report = [];
    // let claim: any;
    this.report = [];
    let item: any;
    for (var i = 0; i < this.packageData.length; i++) {
      item = this.packageData[i];
      this.grievanceBy = [];
      this.grievanceBy.slNo = i + 1;
      // this.sno = [];
      // this.sno.Slno = i + 1;
      this.grievanceBy.grivancename = item.grivancename;
      this.grievanceBy.fullname = item.createdby1.fullname;
      this.grievanceBy.screatedate = item.screatedate;
      if(item.statusFlag==0){
        this.grievanceBy.statusFlag = 'Active';
      }else{
        this.grievanceBy.statusFlag = 'Inactive';
      }

      this.report.push(this.grievanceBy);
      console.log(this.report);
      // console.log(this.grievanceBy);
    }
    if (type == 1) {
      let filter = [];
      TableUtil.exportListToExcelWithFilter(this.report, " Grievance By List", this.heading, filter);
    } else if (type == 2) {
      if (this.report == null || this.report.length == 0) {
        this.swal("Info", "No Record Found", "info");
        return;
      }
      var doc = new jsPDF('l', 'mm', [260, 240]);
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text(" Grievance By List", 110, 10);
      doc.setFontSize(12);
      doc.text("Generated On: " + this.convertDate(new Date()), 25, 33);
      doc.text("Generated By: " + this.sessionService.decryptSessionData("user").fullName, 140, 33);
      var rows = [];
      for (var i = 0; i < this.report.length; i++) {
        var clm = this.report[i];
        var pdf = [];
        pdf[0] = clm.slNo;
        pdf[1] = clm.grivancename;
        pdf[2] = clm.fullname;
        pdf[3] = clm.screatedate;
        pdf[4] = clm.statusFlag;
        rows.push(pdf);
      }
      console.log(rows);
      autoTable(doc, {
        head: this.heading,
        body: rows,
        theme: 'grid',
        startY: 40,
        headStyles: {
          fillColor: [26, 99, 54]
          // fillColor:[30,99,54]
        },
        columnStyles: {
          0: { cellWidth: 30 },
          1: { cellWidth: 55 },
          2: { cellWidth: 65 },
          3: { cellWidth: 45 },
          4: { cellWidth: 40 },
          5: { cellWidth: 50 }
        }
      });
      doc.save('GJAY_ Grievance By List.pdf');
    }
  }

  swal(title: any, text: any, icon: any) {
    Swal.fire({
      icon: icon,
      title: title,
      text: text
    });
  }

  convertDate(date) {
    var datePipe = new DatePipe("en-US");
    date = datePipe.transform(date, 'dd-MMM-yyyy hh:mm:ss a');
    return date;
  }
  pageItemChange() {
    this.pageElement = (<HTMLInputElement>document.getElementById("pageItem")).value;
  }
}


